dataset:
  center_dir: data/dataset_final/center
  dataset_root: data/dataset_final
  patch_size: 256
  train_augment: false
  train_pos_ratio: 0.1
  train_txt: data/train.txt
  use_center_gt: true
  use_width_gt: false
  val_augment: false
  val_pos_ratio: 0.1
  val_txt: data/val.txt
  width_dir: data/dataset_final/width
loss:
  boundary_weight: 0.05
  eccentricity_weight: 0.05
  focal_alpha: 0.5
  focal_gamma: 1.5
  lambda_center: 1.0
  lambda_width: 0.1
  pos_weight: 20.0
  use_center_head: true
  use_eccentricity: true
  use_width_head: false
mlflow:
  experiment: UNetPP-SEM
  run_name: v6_C10_E05
  use: true
model:
  base_filters: 32
  deep_supervision: true
  in_channels: 1
  num_classes: 3
  use_center_head: true
  use_width_head: false
paths:
  checkpoint_dir: checkpoints
  plots_dir: plots
scheduler:
  factor: 0.5
  patience: 5
tags:
  boundary_weight: null
  experiment_group: LOSS_SEARCH
  gamma: null
  model: UNet++_attn_3level
  pweight: null
  train_pos_ratio: null
training:
  batch_size: 4
  epochs: 25
  learning_rate: 0.0001
  metric_threshold: 0.3
  num_workers: 8
  threshold_dice: 0.4
  threshold_iou: 0.4
  threshold_line: 0.3
